# Generated by Django 5.2.4 on 2025-08-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emergency', '0002_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
